# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/feegleweb/octoshoplite/models/product/columns.yaml

# Model Class name
modelClass: Feegleweb\OctoshopLite\Models\Product

# List Title
title: Manage Products

# Link URL for each record
recordUrl: feegleweb/octoshoplite/products/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: created_at
    direction: desc

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar
